on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        auth: ["Bearer $(base64 <<< $GITHUB_TOKEN)", "Basic $(base64 <<< username:$GITHUB_TOKEN)"]

    steps:
      - run: 'curl -X GET -H "Authorization: ${{ matrix.auth }}" https://ghcr.io/v2/jcansdale/gpr/tags/list'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
