on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: 'curl -X GET -H "Authorization: Bearer $(base64 <<< ${{ secrets.READ_PACKAGES_TOKEN }})" https://ghcr.io/v2/jcansdale/gpr/tags/list'
